### ISSUE TITLE
GUI for selecting/coloring/activating subdomains/subcomplexes

### ISSUE THREAD

**Issue by jkosinski** [crosslinks/XlinkAnalyzer#16]
specification - TODO

**Comment by crosslinks** [comment]
This will be probably total re-implementation of the Subunit tab into a panel that looks like Model Panel.

Instead of models it will list subunits, domains and subcomplexes.

As the Model Panel it will have:
- active column
- show column
  Buttons:
- show only
- show
- activate all/only/restore
- write PDB

The activate column will activate Movement Mouse Mode.
